/*
 * Copyright 2022 Realm Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.barqdb.kotlin.internal.interop

actual enum class ErrorCode(actual override val description: String?, actual override val nativeValue: Int) :
    CodeDescription {
    BARQ_ERR_NONE("None", barq_errno_e.BARQ_ERR_NONE),
    BARQ_ERR_RUNTIME("Runtime", barq_errno_e.BARQ_ERR_RUNTIME),
    BARQ_ERR_RANGE_ERROR("RangeError", barq_errno_e.BARQ_ERR_RANGE_ERROR),
    BARQ_ERR_BROKEN_INVARIANT("BrokenInvariant", barq_errno_e.BARQ_ERR_BROKEN_INVARIANT),
    BARQ_ERR_OUT_OF_MEMORY("OutOfMemory", barq_errno_e.BARQ_ERR_OUT_OF_MEMORY),
    BARQ_ERR_OUT_OF_DISK_SPACE("OutOfDiskSpace", barq_errno_e.BARQ_ERR_OUT_OF_DISK_SPACE),
    BARQ_ERR_ADDRESS_SPACE_EXHAUSTED("AddressSpaceExhausted", barq_errno_e.BARQ_ERR_ADDRESS_SPACE_EXHAUSTED),
    BARQ_ERR_MAXIMUM_FILE_SIZE_EXCEEDED("MaximumFileSizeExceeded", barq_errno_e.BARQ_ERR_MAXIMUM_FILE_SIZE_EXCEEDED),
    BARQ_ERR_INCOMPATIBLE_SESSION("IncompatibleSession", barq_errno_e.BARQ_ERR_INCOMPATIBLE_SESSION),
    BARQ_ERR_INCOMPATIBLE_LOCK_FILE("IncompatibleLockFile", barq_errno_e.BARQ_ERR_INCOMPATIBLE_LOCK_FILE),
    BARQ_ERR_INVALID_QUERY("InvalidQuery", barq_errno_e.BARQ_ERR_INVALID_QUERY),
    BARQ_ERR_BAD_VERSION("BadVersion", barq_errno_e.BARQ_ERR_BAD_VERSION),
    BARQ_ERR_UNSUPPORTED_FILE_FORMAT_VERSION("UnsupportedFileFormatVersion", barq_errno_e.BARQ_ERR_UNSUPPORTED_FILE_FORMAT_VERSION),
    BARQ_ERR_MULTIPLE_SYNC_AGENTS("MultipleSyncAgents", barq_errno_e.BARQ_ERR_MULTIPLE_SYNC_AGENTS),
    BARQ_ERR_OBJECT_ALREADY_EXISTS("ObjectAlreadyExists", barq_errno_e.BARQ_ERR_OBJECT_ALREADY_EXISTS),
    BARQ_ERR_NOT_CLONABLE("NotClonable", barq_errno_e.BARQ_ERR_NOT_CLONABLE),
    BARQ_ERR_BAD_CHANGESET("BadChangeset", barq_errno_e.BARQ_ERR_BAD_CHANGESET),
    BARQ_ERR_SUBSCRIPTION_FAILED("SubscriptionFailed", barq_errno_e.BARQ_ERR_SUBSCRIPTION_FAILED),
    BARQ_ERR_FILE_OPERATION_FAILED("FileOperationFailed", barq_errno_e.BARQ_ERR_FILE_OPERATION_FAILED),
    BARQ_ERR_FILE_PERMISSION_DENIED("FilePermissionDenied", barq_errno_e.BARQ_ERR_FILE_PERMISSION_DENIED),
    BARQ_ERR_FILE_NOT_FOUND("FileNotFound", barq_errno_e.BARQ_ERR_FILE_NOT_FOUND),
    BARQ_ERR_FILE_ALREADY_EXISTS("FileAlreadyExists", barq_errno_e.BARQ_ERR_FILE_ALREADY_EXISTS),
    BARQ_ERR_INVALID_DATABASE("InvalidDatabase", barq_errno_e.BARQ_ERR_INVALID_DATABASE),
    BARQ_ERR_DECRYPTION_FAILED("DecryptionFailed", barq_errno_e.BARQ_ERR_DECRYPTION_FAILED),
    BARQ_ERR_INCOMPATIBLE_HISTORIES("IncompatibleHistories", barq_errno_e.BARQ_ERR_INCOMPATIBLE_HISTORIES),
    BARQ_ERR_FILE_FORMAT_UPGRADE_REQUIRED("FileFormatUpgradeRequired", barq_errno_e.BARQ_ERR_FILE_FORMAT_UPGRADE_REQUIRED),
    BARQ_ERR_SCHEMA_VERSION_MISMATCH("SchemaVersionMismatch", barq_errno_e.BARQ_ERR_SCHEMA_VERSION_MISMATCH),
    BARQ_ERR_NO_SUBSCRIPTION_FOR_WRITE("NoSubscriptionForWrite", barq_errno_e.BARQ_ERR_NO_SUBSCRIPTION_FOR_WRITE),
    BARQ_ERR_OPERATION_ABORTED("OperationAborted", barq_errno_e.BARQ_ERR_OPERATION_ABORTED),
    BARQ_ERR_AUTO_CLIENT_RESET_FAILED("AutoClientResetFailed", barq_errno_e.BARQ_ERR_AUTO_CLIENT_RESET_FAILED),
    BARQ_ERR_BAD_SYNC_PARTITION_VALUE("BadSyncPartitionValue", barq_errno_e.BARQ_ERR_BAD_SYNC_PARTITION_VALUE),
    BARQ_ERR_CONNECTION_CLOSED("ConnectionClosed", barq_errno_e.BARQ_ERR_CONNECTION_CLOSED),
    BARQ_ERR_INVALID_SUBSCRIPTION_QUERY("InvalidSubscriptionQuery", barq_errno_e.BARQ_ERR_INVALID_SUBSCRIPTION_QUERY),
    BARQ_ERR_SYNC_CLIENT_RESET_REQUIRED("SyncClientResetRequired", barq_errno_e.BARQ_ERR_SYNC_CLIENT_RESET_REQUIRED),
    BARQ_ERR_SYNC_COMPENSATING_WRITE("CompensatingWrite", barq_errno_e.BARQ_ERR_SYNC_COMPENSATING_WRITE),
    BARQ_ERR_SYNC_CONNECT_FAILED("SyncConnectFailed", barq_errno_e.BARQ_ERR_SYNC_CONNECT_FAILED),
    BARQ_ERR_SYNC_CONNECT_TIMEOUT("SyncConnectTimeout", barq_errno_e.BARQ_ERR_SYNC_CONNECT_TIMEOUT),
    BARQ_ERR_SYNC_INVALID_SCHEMA_CHANGE("SyncInvalidSchemaChange", barq_errno_e.BARQ_ERR_SYNC_INVALID_SCHEMA_CHANGE),
    BARQ_ERR_SYNC_PERMISSION_DENIED("SyncPermissionDenied", barq_errno_e.BARQ_ERR_SYNC_PERMISSION_DENIED),
    BARQ_ERR_SYNC_PROTOCOL_INVARIANT_FAILED("SyncProtocolInvariantFailed", barq_errno_e.BARQ_ERR_SYNC_PROTOCOL_INVARIANT_FAILED),
    BARQ_ERR_SYNC_PROTOCOL_NEGOTIATION_FAILED("SyncProtocolNegotiationFailed", barq_errno_e.BARQ_ERR_SYNC_PROTOCOL_NEGOTIATION_FAILED),
    BARQ_ERR_SYNC_SERVER_PERMISSIONS_CHANGED("SyncServerPermissionsChanged", barq_errno_e.BARQ_ERR_SYNC_SERVER_PERMISSIONS_CHANGED),
    BARQ_ERR_SYNC_USER_MISMATCH("SyncUserMismatch", barq_errno_e.BARQ_ERR_SYNC_USER_MISMATCH),
    BARQ_ERR_TLS_HANDSHAKE_FAILED("TLSHandshakeFailed", barq_errno_e.BARQ_ERR_TLS_HANDSHAKE_FAILED),
    BARQ_ERR_WRONG_SYNC_TYPE("WrongSyncType", barq_errno_e.BARQ_ERR_WRONG_SYNC_TYPE),
    BARQ_ERR_SYNC_WRITE_NOT_ALLOWED("SyncWriteNotAllowed", barq_errno_e.BARQ_ERR_SYNC_WRITE_NOT_ALLOWED),
    BARQ_ERR_SYNC_LOCAL_CLOCK_BEFORE_EPOCH("SyncLocalClockBeforeEpoch", barq_errno_e.BARQ_ERR_SYNC_LOCAL_CLOCK_BEFORE_EPOCH),
    BARQ_ERR_SYNC_SCHEMA_MIGRATION_ERROR("SyncSchemaMigrationError", barq_errno_e.BARQ_ERR_SYNC_SCHEMA_MIGRATION_ERROR),
    BARQ_ERR_SYSTEM_ERROR("SystemError", barq_errno_e.BARQ_ERR_SYSTEM_ERROR),
    BARQ_ERR_LOGIC("Logic", barq_errno_e.BARQ_ERR_LOGIC),
    BARQ_ERR_NOT_SUPPORTED("NotSupported", barq_errno_e.BARQ_ERR_NOT_SUPPORTED),
    BARQ_ERR_BROKEN_PROMISE("BrokenPromise", barq_errno_e.BARQ_ERR_BROKEN_PROMISE),
    BARQ_ERR_CROSS_TABLE_LINK_TARGET("CrossTableLinkTarget", barq_errno_e.BARQ_ERR_CROSS_TABLE_LINK_TARGET),
    BARQ_ERR_KEY_ALREADY_USED("KeyAlreadyUsed", barq_errno_e.BARQ_ERR_KEY_ALREADY_USED),
    BARQ_ERR_WRONG_TRANSACTION_STATE("WrongTransactionState", barq_errno_e.BARQ_ERR_WRONG_TRANSACTION_STATE),
    BARQ_ERR_WRONG_THREAD("WrongThread", barq_errno_e.BARQ_ERR_WRONG_THREAD),
    BARQ_ERR_ILLEGAL_OPERATION("IllegalOperation", barq_errno_e.BARQ_ERR_ILLEGAL_OPERATION),
    BARQ_ERR_SERIALIZATION_ERROR("SerializationError", barq_errno_e.BARQ_ERR_SERIALIZATION_ERROR),
    BARQ_ERR_STALE_ACCESSOR("StaleAccessor", barq_errno_e.BARQ_ERR_STALE_ACCESSOR),
    BARQ_ERR_INVALIDATED_OBJECT("InvalidatedObject", barq_errno_e.BARQ_ERR_INVALIDATED_OBJECT),
    BARQ_ERR_READ_ONLY_DB("ReadOnlyDb", barq_errno_e.BARQ_ERR_READ_ONLY_DB),
    BARQ_ERR_DELETE_OPENED_BARQ("DeleteOpenedBarq", barq_errno_e.BARQ_ERR_DELETE_OPENED_BARQ),
    BARQ_ERR_MISMATCHED_CONFIG("MismatchedConfig", barq_errno_e.BARQ_ERR_MISMATCHED_CONFIG),
    BARQ_ERR_CLOSED_BARQ("ClosedBarq", barq_errno_e.BARQ_ERR_CLOSED_BARQ),
    BARQ_ERR_INVALID_TABLE_REF("InvalidTableRef", barq_errno_e.BARQ_ERR_INVALID_TABLE_REF),
    BARQ_ERR_SCHEMA_VALIDATION_FAILED("SchemaValidationFailed", barq_errno_e.BARQ_ERR_SCHEMA_VALIDATION_FAILED),
    BARQ_ERR_SCHEMA_MISMATCH("SchemaMismatch", barq_errno_e.BARQ_ERR_SCHEMA_MISMATCH),
    BARQ_ERR_INVALID_SCHEMA_VERSION("InvalidSchemaVersion", barq_errno_e.BARQ_ERR_INVALID_SCHEMA_VERSION),
    BARQ_ERR_INVALID_SCHEMA_CHANGE("InvalidSchemaChange", barq_errno_e.BARQ_ERR_INVALID_SCHEMA_CHANGE),
    BARQ_ERR_MIGRATION_FAILED("MigrationFailed", barq_errno_e.BARQ_ERR_MIGRATION_FAILED),
    BARQ_ERR_TOP_LEVEL_OBJECT("TopLevelObject", barq_errno_e.BARQ_ERR_TOP_LEVEL_OBJECT),
    BARQ_ERR_INVALID_ARGUMENT("InvalidArgument", barq_errno_e.BARQ_ERR_INVALID_ARGUMENT),
    BARQ_ERR_PROPERTY_TYPE_MISMATCH("PropertyTypeMismatch", barq_errno_e.BARQ_ERR_PROPERTY_TYPE_MISMATCH),
    BARQ_ERR_PROPERTY_NOT_NULLABLE("PropertyNotNullable", barq_errno_e.BARQ_ERR_PROPERTY_NOT_NULLABLE),
    BARQ_ERR_READ_ONLY_PROPERTY("ReadOnlyProperty", barq_errno_e.BARQ_ERR_READ_ONLY_PROPERTY),
    BARQ_ERR_MISSING_PROPERTY_VALUE("MissingPropertyValue", barq_errno_e.BARQ_ERR_MISSING_PROPERTY_VALUE),
    BARQ_ERR_MISSING_PRIMARY_KEY("MissingPrimaryKey", barq_errno_e.BARQ_ERR_MISSING_PRIMARY_KEY),
    BARQ_ERR_UNEXPECTED_PRIMARY_KEY("UnexpectedPrimaryKey", barq_errno_e.BARQ_ERR_UNEXPECTED_PRIMARY_KEY),
    BARQ_ERR_MODIFY_PRIMARY_KEY("ModifyPrimaryKey", barq_errno_e.BARQ_ERR_MODIFY_PRIMARY_KEY),
    BARQ_ERR_INVALID_QUERY_STRING("InvalidQueryString", barq_errno_e.BARQ_ERR_INVALID_QUERY_STRING),
    BARQ_ERR_INVALID_PROPERTY("InvalidProperty", barq_errno_e.BARQ_ERR_INVALID_PROPERTY),
    BARQ_ERR_INVALID_NAME("InvalidName", barq_errno_e.BARQ_ERR_INVALID_NAME),
    BARQ_ERR_INVALID_DICTIONARY_KEY("InvalidDictionaryKey", barq_errno_e.BARQ_ERR_INVALID_DICTIONARY_KEY),
    BARQ_ERR_INVALID_DICTIONARY_VALUE("InvalidDictionaryValue", barq_errno_e.BARQ_ERR_INVALID_DICTIONARY_VALUE),
    BARQ_ERR_INVALID_SORT_DESCRIPTOR("InvalidSortDescriptor", barq_errno_e.BARQ_ERR_INVALID_SORT_DESCRIPTOR),
    BARQ_ERR_INVALID_ENCRYPTION_KEY("InvalidEncryptionKey", barq_errno_e.BARQ_ERR_INVALID_ENCRYPTION_KEY),
    BARQ_ERR_INVALID_QUERY_ARG("InvalidQueryArg", barq_errno_e.BARQ_ERR_INVALID_QUERY_ARG),
    BARQ_ERR_NO_SUCH_OBJECT("NoSuchObject", barq_errno_e.BARQ_ERR_NO_SUCH_OBJECT),
    BARQ_ERR_INDEX_OUT_OF_BOUNDS("IndexOutOfBounds", barq_errno_e.BARQ_ERR_INDEX_OUT_OF_BOUNDS),
    BARQ_ERR_LIMIT_EXCEEDED("LimitExceeded", barq_errno_e.BARQ_ERR_LIMIT_EXCEEDED),
    BARQ_ERR_OBJECT_TYPE_MISMATCH("ObjectTypeMismatch", barq_errno_e.BARQ_ERR_OBJECT_TYPE_MISMATCH),
    BARQ_ERR_NO_SUCH_TABLE("NoSuchTable", barq_errno_e.BARQ_ERR_NO_SUCH_TABLE),
    BARQ_ERR_TABLE_NAME_IN_USE("TableNameInUse", barq_errno_e.BARQ_ERR_TABLE_NAME_IN_USE),
    BARQ_ERR_ILLEGAL_COMBINATION("IllegalCombination", barq_errno_e.BARQ_ERR_ILLEGAL_COMBINATION),
    BARQ_ERR_BAD_SERVER_URL("BadServerUrl", barq_errno_e.BARQ_ERR_BAD_SERVER_URL),
    BARQ_ERR_CUSTOM_ERROR("CustomError", barq_errno_e.BARQ_ERR_CUSTOM_ERROR),
    BARQ_ERR_CLIENT_USER_NOT_FOUND("ClientUserNotFound", barq_errno_e.BARQ_ERR_CLIENT_USER_NOT_FOUND),
    BARQ_ERR_CLIENT_USER_NOT_LOGGED_IN("ClientUserNotLoggedIn", barq_errno_e.BARQ_ERR_CLIENT_USER_NOT_LOGGED_IN),
    BARQ_ERR_CLIENT_REDIRECT_ERROR("ClientRedirectError", barq_errno_e.BARQ_ERR_CLIENT_REDIRECT_ERROR),
    BARQ_ERR_CLIENT_TOO_MANY_REDIRECTS("ClientTooManyRedirects", barq_errno_e.BARQ_ERR_CLIENT_TOO_MANY_REDIRECTS),
    BARQ_ERR_CLIENT_USER_ALREADY_NAMED("ClientUserAlreadyNamed", barq_errno_e.BARQ_ERR_CLIENT_USER_ALREADY_NAMED),
    BARQ_ERR_BAD_TOKEN("BadToken", barq_errno_e.BARQ_ERR_BAD_TOKEN),
    BARQ_ERR_MALFORMED_JSON("MalformedJson", barq_errno_e.BARQ_ERR_MALFORMED_JSON),
    BARQ_ERR_MISSING_JSON_KEY("MissingJsonKey", barq_errno_e.BARQ_ERR_MISSING_JSON_KEY),
    BARQ_ERR_MISSING_AUTH_REQ("MissingAuthReq", barq_errno_e.BARQ_ERR_MISSING_AUTH_REQ),
    BARQ_ERR_INVALID_SESSION("InvalidSession", barq_errno_e.BARQ_ERR_INVALID_SESSION),
    BARQ_ERR_USER_APP_DOMAIN_MISMATCH("UserAppDomainMismatch", barq_errno_e.BARQ_ERR_USER_APP_DOMAIN_MISMATCH),
    BARQ_ERR_DOMAIN_NOT_ALLOWED("DomainNotAllowed", barq_errno_e.BARQ_ERR_DOMAIN_NOT_ALLOWED),
    BARQ_ERR_READ_SIZE_LIMIT_EXCEEDED("ReadSizeLimitExceeded", barq_errno_e.BARQ_ERR_READ_SIZE_LIMIT_EXCEEDED),
    BARQ_ERR_INVALID_PARAMETER("InvalidParameter", barq_errno_e.BARQ_ERR_INVALID_PARAMETER),
    BARQ_ERR_MISSING_PARAMETER("MissingParameter", barq_errno_e.BARQ_ERR_MISSING_PARAMETER),
    BARQ_ERR_TWILIO_ERROR("TwilioError", barq_errno_e.BARQ_ERR_TWILIO_ERROR),
    BARQ_ERR_GCM_ERROR("GcmError", barq_errno_e.BARQ_ERR_GCM_ERROR),
    BARQ_ERR_HTTP_ERROR("HttpError", barq_errno_e.BARQ_ERR_HTTP_ERROR),
    BARQ_ERR_AWS_ERROR("AwsError", barq_errno_e.BARQ_ERR_AWS_ERROR),
    BARQ_ERR_ARGUMENTS_NOT_ALLOWED("ArgumentsNotAllowed", barq_errno_e.BARQ_ERR_ARGUMENTS_NOT_ALLOWED),
    BARQ_ERR_FUNCTION_EXECUTION_ERROR("FunctionExecutionError", barq_errno_e.BARQ_ERR_FUNCTION_EXECUTION_ERROR),
    BARQ_ERR_NO_MATCHING_RULE("NoMatchingRule", barq_errno_e.BARQ_ERR_NO_MATCHING_RULE_FOUND),
    BARQ_ERR_INTERNAL_SERVER_ERROR("InternalServerError", barq_errno_e.BARQ_ERR_INTERNAL_SERVER_ERROR),
    BARQ_ERR_AUTH_PROVIDER_NOT_FOUND("AuthProviderNotFound", barq_errno_e.BARQ_ERR_AUTH_PROVIDER_NOT_FOUND),
    BARQ_ERR_AUTH_PROVIDER_ALREADY_EXISTS("AuthProviderAlreadyExists", barq_errno_e.BARQ_ERR_AUTH_PROVIDER_ALREADY_EXISTS),
    BARQ_ERR_SERVICE_NOT_FOUND("ServiceNotFound", barq_errno_e.BARQ_ERR_SERVICE_NOT_FOUND),
    BARQ_ERR_SERVICE_TYPE_NOT_FOUND("ServiceTypeNotFound", barq_errno_e.BARQ_ERR_SERVICE_TYPE_NOT_FOUND),
    BARQ_ERR_SERVICE_ALREADY_EXISTS("ServiceAlreadyExists", barq_errno_e.BARQ_ERR_SERVICE_ALREADY_EXISTS),
    BARQ_ERR_SERVICE_COMMAND_NOT_FOUND("ServiceCommandNotFound", barq_errno_e.BARQ_ERR_SERVICE_COMMAND_NOT_FOUND),
    BARQ_ERR_VALUE_NOT_FOUND("ValueNotFound", barq_errno_e.BARQ_ERR_VALUE_NOT_FOUND),
    BARQ_ERR_VALUE_ALREADY_EXISTS("ValueAlreadyExists", barq_errno_e.BARQ_ERR_VALUE_ALREADY_EXISTS),
    BARQ_ERR_VALUE_DUPLICATE_NAME("ValueDuplicateName", barq_errno_e.BARQ_ERR_VALUE_DUPLICATE_NAME),
    BARQ_ERR_FUNCTION_NOT_FOUND("FunctionNotFound", barq_errno_e.BARQ_ERR_FUNCTION_NOT_FOUND),
    BARQ_ERR_FUNCTION_ALREADY_EXISTS("FunctionAlreadyExists", barq_errno_e.BARQ_ERR_FUNCTION_ALREADY_EXISTS),
    BARQ_ERR_FUNCTION_DUPLICATE_NAME("FunctionDuplicateName", barq_errno_e.BARQ_ERR_FUNCTION_DUPLICATE_NAME),
    BARQ_ERR_FUNCTION_SYNTAX_ERROR("FunctionSyntaxError", barq_errno_e.BARQ_ERR_FUNCTION_SYNTAX_ERROR),
    BARQ_ERR_FUNCTION_INVALID("FunctionInvalid", barq_errno_e.BARQ_ERR_FUNCTION_INVALID),
    BARQ_ERR_INCOMING_WEBHOOK_NOT_FOUND("IncomingWebhookNotFound", barq_errno_e.BARQ_ERR_INCOMING_WEBHOOK_NOT_FOUND),
    BARQ_ERR_INCOMING_WEBHOOK_ALREADY_EXISTS("IncomingWebhookAlreadyExists", barq_errno_e.BARQ_ERR_INCOMING_WEBHOOK_ALREADY_EXISTS),
    BARQ_ERR_INCOMING_WEBHOOK_DUPLICATE_NAME("IncomingWebhookDuplicateName", barq_errno_e.BARQ_ERR_INCOMING_WEBHOOK_DUPLICATE_NAME),
    BARQ_ERR_RULE_NOT_FOUND("RuleNotFound", barq_errno_e.BARQ_ERR_RULE_NOT_FOUND),
    BARQ_ERR_API_KEY_NOT_FOUND("ApiKeyNotFound", barq_errno_e.BARQ_ERR_API_KEY_NOT_FOUND),
    BARQ_ERR_RULE_ALREADY_EXISTS("RuleAlreadyExists", barq_errno_e.BARQ_ERR_RULE_ALREADY_EXISTS),
    BARQ_ERR_RULE_DUPLICATE_NAME("RuleDuplicateName", barq_errno_e.BARQ_ERR_RULE_DUPLICATE_NAME),
    BARQ_ERR_AUTH_PROVIDER_DUPLICATE_NAME("AuthProviderDuplicateName", barq_errno_e.BARQ_ERR_AUTH_PROVIDER_DUPLICATE_NAME),
    BARQ_ERR_RESTRICTED_HOST("RestrictedHost", barq_errno_e.BARQ_ERR_RESTRICTED_HOST),
    BARQ_ERR_API_KEY_ALREADY_EXISTS("ApiKeyAlreadyExists", barq_errno_e.BARQ_ERR_API_KEY_ALREADY_EXISTS),
    BARQ_ERR_INCOMING_WEBHOOK_AUTH_FAILED("IncomingWebhookAuthFailed", barq_errno_e.BARQ_ERR_INCOMING_WEBHOOK_AUTH_FAILED),
    BARQ_ERR_EXECUTION_TIME_LIMIT_EXCEEDED("ExecutionTimeLimitExceeded", barq_errno_e.BARQ_ERR_EXECUTION_TIME_LIMIT_EXCEEDED),
    BARQ_ERR_NOT_CALLABLE("NotCallable", barq_errno_e.BARQ_ERR_NOT_CALLABLE),
    BARQ_ERR_USER_ALREADY_CONFIRMED("UserAlreadyConfirmed", barq_errno_e.BARQ_ERR_USER_ALREADY_CONFIRMED),
    BARQ_ERR_USER_NOT_FOUND("UserNotFound", barq_errno_e.BARQ_ERR_USER_NOT_FOUND),
    BARQ_ERR_USER_DISABLED("UserDisabled", barq_errno_e.BARQ_ERR_USER_DISABLED),
    BARQ_ERR_AUTH_ERROR("AuthError", barq_errno_e.BARQ_ERR_AUTH_ERROR),
    BARQ_ERR_BAD_REQUEST("BadRequest", barq_errno_e.BARQ_ERR_BAD_REQUEST),
    BARQ_ERR_ACCOUNT_NAME_IN_USE("AccountNameInUse", barq_errno_e.BARQ_ERR_ACCOUNT_NAME_IN_USE),
    BARQ_ERR_INVALID_PASSWORD("InvalidPassword", barq_errno_e.BARQ_ERR_INVALID_PASSWORD),
    BARQ_ERR_SCHEMA_VALIDATION_FAILED_WRITE("SchemaValidationFailedWrite", barq_errno_e.BARQ_ERR_SCHEMA_VALIDATION_FAILED_WRITE),
    BARQ_ERR_APP_UNKNOWN("Unknown", barq_errno_e.BARQ_ERR_APP_UNKNOWN),
    BARQ_ERR_MAINTENANCE_IN_PROGRESS("MaintenanceInProgress", barq_errno_e.BARQ_ERR_MAINTENANCE_IN_PROGRESS),
    BARQ_ERR_USERPASS_TOKEN_INVALID("UserpassTokenInvalid", barq_errno_e.BARQ_ERR_USERPASS_TOKEN_INVALID),
    BARQ_ERR_INVALID_SERVER_RESPONSE("InvalidServerResponse", barq_errno_e.BARQ_ERR_INVALID_SERVER_RESPONSE),
    BARQ_ERR_APP_SERVER_ERROR("AppServerError", barq_errno_e.BARQ_ERR_APP_SERVER_ERROR),
    BARQ_ERR_CALLBACK("Callback", barq_errno_e.BARQ_ERR_CALLBACK),
    BARQ_ERR_UNKNOWN("Unknown", barq_errno_e.BARQ_ERR_UNKNOWN);

    actual companion object {
        actual fun of(nativeValue: Int): ErrorCode? =
            values().firstOrNull { value ->
                value.nativeValue == nativeValue
            }
    }
}
