/*
 * Copyright 2022 Realm Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package io.github.barqdb.kotlin.internal.interop.sync

import io.github.barqdb.kotlin.internal.interop.CodeDescription

/**
 * Wrapper for C-API `barq_sync_errno_connection`.
 * See https://github.com/BarqDB/barq-core/blob/master/src/barq/error_codes.h#L209
 */
expect enum class SyncConnectionErrorCode : CodeDescription {
    BARQ_SYNC_ERR_CONNECTION_CONNECTION_CLOSED,
    BARQ_SYNC_ERR_CONNECTION_OTHER_ERROR,
    BARQ_SYNC_ERR_CONNECTION_UNKNOWN_MESSAGE,
    BARQ_SYNC_ERR_CONNECTION_BAD_SYNTAX,
    BARQ_SYNC_ERR_CONNECTION_LIMITS_EXCEEDED,
    BARQ_SYNC_ERR_CONNECTION_WRONG_PROTOCOL_VERSION,
    BARQ_SYNC_ERR_CONNECTION_BAD_SESSION_IDENT,
    BARQ_SYNC_ERR_CONNECTION_REUSE_OF_SESSION_IDENT,
    BARQ_SYNC_ERR_CONNECTION_BOUND_IN_OTHER_SESSION,
    BARQ_SYNC_ERR_CONNECTION_BAD_MESSAGE_ORDER,
    BARQ_SYNC_ERR_CONNECTION_BAD_DECOMPRESSION,
    BARQ_SYNC_ERR_CONNECTION_BAD_CHANGESET_HEADER_SYNTAX,
    BARQ_SYNC_ERR_CONNECTION_BAD_CHANGESET_SIZE,
    BARQ_SYNC_ERR_CONNECTION_SWITCH_TO_FLX_SYNC,
    BARQ_SYNC_ERR_CONNECTION_SWITCH_TO_PBS;

    override val nativeValue: Int
    override val description: String?
}

/**
 * Wrapper for C-API `barq_sync_errno_session`.
 * See https://github.com/BarqDB/barq-core/blob/master/src/barq/error_codes.h#L228
 */
expect enum class SyncSessionErrorCode : CodeDescription {
    BARQ_SYNC_ERR_SESSION_SESSION_CLOSED,
    BARQ_SYNC_ERR_SESSION_OTHER_SESSION_ERROR,
    BARQ_SYNC_ERR_SESSION_TOKEN_EXPIRED,
    BARQ_SYNC_ERR_SESSION_BAD_AUTHENTICATION,
    BARQ_SYNC_ERR_SESSION_ILLEGAL_BARQ_PATH,
    BARQ_SYNC_ERR_SESSION_NO_SUCH_BARQ,
    BARQ_SYNC_ERR_SESSION_PERMISSION_DENIED,
    BARQ_SYNC_ERR_SESSION_BAD_SERVER_FILE_IDENT,
    BARQ_SYNC_ERR_SESSION_BAD_CLIENT_FILE_IDENT,
    BARQ_SYNC_ERR_SESSION_BAD_SERVER_VERSION,
    BARQ_SYNC_ERR_SESSION_BAD_CLIENT_VERSION,
    BARQ_SYNC_ERR_SESSION_DIVERGING_HISTORIES,
    BARQ_SYNC_ERR_SESSION_BAD_CHANGESET,
    BARQ_SYNC_ERR_SESSION_PARTIAL_SYNC_DISABLED,
    BARQ_SYNC_ERR_SESSION_UNSUPPORTED_SESSION_FEATURE,
    BARQ_SYNC_ERR_SESSION_BAD_ORIGIN_FILE_IDENT,
    BARQ_SYNC_ERR_SESSION_BAD_CLIENT_FILE,
    BARQ_SYNC_ERR_SESSION_SERVER_FILE_DELETED,
    BARQ_SYNC_ERR_SESSION_CLIENT_FILE_BLACKLISTED,
    BARQ_SYNC_ERR_SESSION_USER_BLACKLISTED,
    BARQ_SYNC_ERR_SESSION_TRANSACT_BEFORE_UPLOAD,
    BARQ_SYNC_ERR_SESSION_CLIENT_FILE_EXPIRED,
    BARQ_SYNC_ERR_SESSION_USER_MISMATCH,
    BARQ_SYNC_ERR_SESSION_TOO_MANY_SESSIONS,
    BARQ_SYNC_ERR_SESSION_INVALID_SCHEMA_CHANGE,
    BARQ_SYNC_ERR_SESSION_BAD_QUERY,
    BARQ_SYNC_ERR_SESSION_OBJECT_ALREADY_EXISTS,
    BARQ_SYNC_ERR_SESSION_SERVER_PERMISSIONS_CHANGED,
    BARQ_SYNC_ERR_SESSION_INITIAL_SYNC_NOT_COMPLETED,
    BARQ_SYNC_ERR_SESSION_WRITE_NOT_ALLOWED,
    BARQ_SYNC_ERR_SESSION_COMPENSATING_WRITE,
    BARQ_SYNC_ERR_SESSION_MIGRATE_TO_FLX,
    BARQ_SYNC_ERR_SESSION_BAD_PROGRESS,
    BARQ_SYNC_ERR_SESSION_REVERT_TO_PBS,
    BARQ_SYNC_ERR_SESSION_BAD_SCHEMA_VERSION,
    BARQ_SYNC_ERR_SESSION_SCHEMA_VERSION_CHANGED;

    override val nativeValue: Int
    override val description: String?
}

/**
 * Wrapper for C-API `barq_web_socket_errno`.
 * See https://github.com/BarqDB/barq-core/blob/master/src/barq/error_codes.h#L266
 */
expect enum class WebsocketErrorCode : CodeDescription {
    BARQ_ERR_WEBSOCKET_OK,
    BARQ_ERR_WEBSOCKET_GOINGAWAY,
    BARQ_ERR_WEBSOCKET_PROTOCOLERROR,
    BARQ_ERR_WEBSOCKET_UNSUPPORTEDDATA,
    BARQ_ERR_WEBSOCKET_RESERVED,
    BARQ_ERR_WEBSOCKET_NOSTATUSRECEIVED,
    BARQ_ERR_WEBSOCKET_ABNORMALCLOSURE,
    BARQ_ERR_WEBSOCKET_INVALIDPAYLOADDATA,
    BARQ_ERR_WEBSOCKET_POLICYVIOLATION,
    BARQ_ERR_WEBSOCKET_MESSAGETOOBIG,
    BARQ_ERR_WEBSOCKET_INAVALIDEXTENSION,
    BARQ_ERR_WEBSOCKET_INTERNALSERVERERROR,
    BARQ_ERR_WEBSOCKET_TLSHANDSHAKEFAILED,
    BARQ_ERR_WEBSOCKET_UNAUTHORIZED,
    BARQ_ERR_WEBSOCKET_FORBIDDEN,
    BARQ_ERR_WEBSOCKET_MOVEDPERMANENTLY,
    BARQ_ERR_WEBSOCKET_RESOLVE_FAILED,
    BARQ_ERR_WEBSOCKET_CONNECTION_FAILED,
    BARQ_ERR_WEBSOCKET_READ_ERROR,
    BARQ_ERR_WEBSOCKET_WRITE_ERROR,
    BARQ_ERR_WEBSOCKET_RETRY_ERROR,
    BARQ_ERR_WEBSOCKET_FATAL_ERROR;

    override val nativeValue: Int
    override val description: String?
}

/**
 * Wrapper for C-API `barq_sync_socket_callback_result`
 * See https://github.com/BarqDB/barq-core/blob/master/src/barq/error_codes.h#L298
 */
expect enum class WebsocketCallbackResult : CodeDescription {
    BARQ_ERR_SYNC_SOCKET_SUCCESS,
    BARQ_ERR_SYNC_SOCKET_OPERATION_ABORTED,
    BARQ_ERR_SYNC_SOCKET_RUNTIME,
    BARQ_ERR_SYNC_SOCKET_OUT_OF_MEMORY,
    BARQ_ERR_SYNC_SOCKET_ADDRESS_SPACE_EXHAUSTED,
    BARQ_ERR_SYNC_SOCKET_CONNECTION_CLOSED,
    BARQ_ERR_SYNC_SOCKET_NOT_SUPPORTED,
    BARQ_ERR_SYNC_SOCKET_INVALID_ARGUMENT;

    override val nativeValue: Int
    override val description: String?
}
